### ISSUE TITLE
What's your bios version?

### ISSUE THREAD

**Issue by aiello3-wolai** [Boos4721/Hackintosh-GA-Z170n-WIFI-OC#1]
Hello, thanks for your repo. My motherboard bios version is `f20g`, and cant boot macOS from OC. What's your bios version? thank you.

**Comment by Boos4721** [comment]
official lasest version

**Comment by Boos4721** [comment]
link here: https://download.gigabyte.cn/FileList/BIOS/mb_bios_ga-z170n-wifi_f20i.zip?v=e214777a7a78ee2bcb80e6ad1ebb3a88
